export const GOOGLE_MAPS_API_KEY = 'YOUR_GOOGLE_MAPS_API_KEY';
export const GOOGLE_OAUTH_CLIENT_ID = 'YOUR_GOOGLE_OAUTH_CLIENT_ID';
export const GOOGLE_SHEETS_SPREADSHEET_ID = 'YOUR_SPREADSHEET_ID';
export const GOOGLE_SHEETS_TAB_NAME = 'Clients';
